<a href="https://colab.research.google.com/github/troymerales/python-notebooks-nm/blob/main/RREF_and_REF_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Row echelon form (REF)

This notebook shows my code for reducing a matrix into its row echelon form. A matrix is in row echelon from if:

1.   All nonzero rows are above any rows of all zeros.
2.   The leading non-zero entry of each row is to the right of the leading entry in the row above it.
3. All entries below each leading entry are zeros.

In [ ]:
import numpy as np

def ref(A):
  A=A.astype(float)
  row, col = A.shape
  iter=0

  print(f"A = {A}\n\n\nSolution: \n")

  for i in range(row):
    if A[i][i] == 0:
      for r in range(i+1, row):
        if A[r][i] != 0:
          A[i], A[r] = A[r], A[i].copy()
          iter+=1
          print(f"{iter}. Swapped R{i+1} and R{r+1}\n{A}\n")
          break
    denom=A[i][i]
    A[i]=A[i]/A[i][i]
    iter+=1
    print(f"{iter}. R{i+1} = R{i+1}/{denom}\n{A}\n")

    for r in range(i+1,row):
      coef=A[r][i]
      A[r]=A[r]-(A[r][i]*A[i])
      iter+=1
      print(f"{iter}. R{r+1} = R{r+1} - {coef}R{i+1}\n{A}\n")

  print(f"\n\nREF Form: \n{A}")

In [ ]:
A = np.array([[2, 1, -1, 8],
              [-3, -1, 2, -11],
              [-2, 1, 2, -3]], dtype=float)
ref(A)

A = [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]


Solution: 

1. R1 = R1/2.0
[[  1.    0.5  -0.5   4. ]
 [ -3.   -1.    2.  -11. ]
 [ -2.    1.    2.   -3. ]]

2. R2 = R2 - -3.0R1
[[ 1.   0.5 -0.5  4. ]
 [ 0.   0.5  0.5  1. ]
 [-2.   1.   2.  -3. ]]

3. R3 = R3 - -2.0R1
[[ 1.   0.5 -0.5  4. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

4. R2 = R2/0.5
[[ 1.   0.5 -0.5  4. ]
 [ 0.   1.   1.   2. ]
 [ 0.   2.   1.   5. ]]

5. R3 = R3 - 2.0R2
[[ 1.   0.5 -0.5  4. ]
 [ 0.   1.   1.   2. ]
 [ 0.   0.  -1.   1. ]]

6. R3 = R3/-1.0
[[ 1.   0.5 -0.5  4. ]
 [ 0.   1.   1.   2. ]
 [-0.  -0.   1.  -1. ]]



REF Form: 
[[ 1.   0.5 -0.5  4. ]
 [ 0.   1.   1.   2. ]
 [-0.  -0.   1.  -1. ]]


# Reduced row echelon form (RREF)
A matrix is in reduced row echelon form if:
1. All leading entries or pivots are 1.
2. Each pivot is the only nonzero entry in its column.
3. Each pivot appears to the right of the pivot in the row above.
4. Any row with all zero entries is at the bottom.

We will reuse the `ref` function and start from there.

In [ ]:
import numpy as np

def rref(A):
  row, col = A.shape
  A = A.astype(float)
  iter=0

  print(f"A = {A}\n\n\n")

  for i in range(row):
    if A[i][i] == 0:
      for r in range(i+1, row):
        if A[r][i] != 0:
          A[i], A[r] = A[r], A[i].copy()
          print(f"{iter}. Swapped R{i+1} and R{r+1}\n{A}\n")
          break

    denom=A[i][i]
    iter+=1
    print(f"{iter}. R{i+1} = R{i+1}/{denom}\n{A}\n")
    A[i] = A[i] / A[i][i]
    for r in range(i+1, row):
      coef=A[r][i]
      A[r] = A[r] - A[r][i] * A[i]
      iter+=1
      print(f"{iter}. R{r+1} = R{r+1} - {coef}R{i+1}\n{A}\n")

  for i in reversed(range(row)):
    for r in range(i):
      coef=A[r][i]
      A[r] = A[r] - A[r][i] * A[i]
      iter+=1
      print(f"{iter}. R{r+1} = R{r+1} - {coef}R{i+1}\n{A}\n")

In [ ]:
A = np.array([[1, 2, -1, -4],
              [2, 3, -1, -11],
              [-2, 0, -3, 22]], dtype=float)

rref(A)

A = [[  1.   2.  -1.  -4.]
 [  2.   3.  -1. -11.]
 [ -2.   0.  -3.  22.]]



1. R1 = R1/1.0
[[  1.   2.  -1.  -4.]
 [  2.   3.  -1. -11.]
 [ -2.   0.  -3.  22.]]

2. R2 = R2 - 2.0R1
[[ 1.  2. -1. -4.]
 [ 0. -1.  1. -3.]
 [-2.  0. -3. 22.]]

3. R3 = R3 - -2.0R1
[[ 1.  2. -1. -4.]
 [ 0. -1.  1. -3.]
 [ 0.  4. -5. 14.]]

4. R2 = R2/-1.0
[[ 1.  2. -1. -4.]
 [ 0. -1.  1. -3.]
 [ 0.  4. -5. 14.]]

5. R3 = R3 - 4.0R2
[[ 1.  2. -1. -4.]
 [-0.  1. -1.  3.]
 [ 0.  0. -1.  2.]]

6. R3 = R3/-1.0
[[ 1.  2. -1. -4.]
 [-0.  1. -1.  3.]
 [ 0.  0. -1.  2.]]

7. R1 = R1 - -1.0R3
[[ 1.  2.  0. -6.]
 [-0.  1. -1.  3.]
 [-0. -0.  1. -2.]]

8. R2 = R2 - -1.0R3
[[ 1.  2.  0. -6.]
 [-0.  1.  0.  1.]
 [-0. -0.  1. -2.]]

9. R1 = R1 - 2.0R2
[[ 1.  0.  0. -8.]
 [-0.  1.  0.  1.]
 [-0. -0.  1. -2.]]



array([[ 1.,  0.,  0., -8.],
       [-0.,  1.,  0.,  1.],
       [-0., -0.,  1., -2.]])